(ns blackjack-test
  (:require [blackjack]
            [clojure.test :refer [deftest is]]))

; copied from https://github.com/exercism/go/blob/main/exercises/concept/blackjack/blackjack_test.go

(deftest test-parse-card
  (is (= 2 (blackjack/parse-card "2")))
  (is (= 5 (blackjack/parse-card "5")))
  (is (= 8 (blackjack/parse-card "8")))
  (is (= 11 (blackjack/parse-card "A")))
  (is (= 10 (blackjack/parse-card "10")))
  (is (= 10 (blackjack/parse-card "J")))
  (is (= 10 (blackjack/parse-card "Q")))
  (is (= 10 (blackjack/parse-card "K"))))

(deftest test-first-hand
  (is (= "P" (blackjack/first-turn "A" "A" "A")))
  (is (= "S" (blackjack/first-turn "J" "J" "A")))
  (is (= "S" (blackjack/first-turn "K" "K" "A")))
  (is (= "H" (blackjack/first-turn "2" "2" "A")))
  (is (= "H" (blackjack/first-turn "5" "5" "A")))
  (is (= "S" (blackjack/first-turn "A" "J" "A")))
  (is (= "S" (blackjack/first-turn "K" "A" "Q")))
  (is (= "S" (blackjack/first-turn "K" "A" "Q")))
  (is (= "W" (blackjack/first-turn "A" "10" "5")))
  (is (= "W" (blackjack/first-turn "A" "K" "9")))
  (is (= "S" (blackjack/first-turn "10" "K" "A")))
  (is (= "S" (blackjack/first-turn "10" "9" "A")))
  (is (= "S" (blackjack/first-turn "10" "8" "A")))
  (is (= "S" (blackjack/first-turn "7" "K" "A")))
  (is (= "S" (blackjack/first-turn "10" "6" "6")))
  (is (= "H" (blackjack/first-turn "10" "6" "7")))
  (is (= "H" (blackjack/first-turn "10" "6" "7")))
  (is (= "H" (blackjack/first-turn "10" "6" "A")))
  (is (= "S" (blackjack/first-turn "10" "5" "6")))
  (is (= "H" (blackjack/first-turn "10" "5" "7")))
  (is (= "H" (blackjack/first-turn "10" "5" "K")))
  (is (= "S" (blackjack/first-turn "10" "4" "6")))
  (is (= "H" (blackjack/first-turn "10" "4" "7")))
  (is (= "H" (blackjack/first-turn "10" "4" "Q")))
  (is (= "S" (blackjack/first-turn "10" "3" "6")))
  (is (= "H" (blackjack/first-turn "10" "3" "7")))
  (is (= "H" (blackjack/first-turn "10" "3" "Q")))
  (is (= "S" (blackjack/first-turn "10" "2" "6")))
  (is (= "H" (blackjack/first-turn "10" "2" "7")))
  (is (= "H" (blackjack/first-turn "10" "2" "Q")))
  (is (= "H" (blackjack/first-turn "9" "2" "Q")))
  (is (= "H" (blackjack/first-turn "8" "2" "2")))
  (is (= "H" (blackjack/first-turn "3" "2" "Q")))
  (is (= "H" (blackjack/first-turn "2" "2" "5")))
  )
